# variables:
#   CS_MAJOR_VERSION: 3

stages:
  - test
  - update

test:
  stage: test
  image: registry.orr.noaa.gov/erd/centos-conda/centos7-python3.9
  tags:
    - docker

  except:
    - schedules

  artifacts:
    paths:
      - validation_by_record.rst
      - validation_by_error.rst
      - validation_by_error.html
      - validation_by_record.html
      - data

  before_script:
    - echo "ip_resolve=4" >> /etc/yum.conf
    # - yum update -y
    # - conda install -y python=3.9
    # - conda update -y conda
    - |-
        if [[ $CI_COMMIT_BRANCH = "production" ]]; then
          BRANCH="production"
        else
          BRANCH="develop"
        fi

  script:
    - echo "running the scripts"
    - git status
    - pwd
    - echo "cloning ${BRANCH}"
#    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/oil_database/oildb-deploy.gi
#   note: this should be master, once things settle down.
    - git clone --depth 1 -b ${BRANCH} https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/oil_database/oil_database.git
    - pwd
    - ls
    - cd oil_database
    - conda install -y --file adios_db/conda_requirements.txt docutils

    # Install the adios_db package
    - cd adios_db
    - pip install -e ./
    - cd ../../
    # this will normalize records and update status
    # The status list inside the records -- and saved in artifacts to be updated in git
    #    at the next stage
    - adios_db_process_json ./data/oil/ save
    # so we can see what's changed:
    - git status
    - adios_db_validate ./data/oil save
    - rst2html.py validation_by_record.rst > validation_by_record.html
    - rst2html.py validation_by_error.rst > validation_by_error.html
  only:
    changes:
      - .gitlab-ci.yml
      - data/**/*

update_validation_report:
  stage: update
  tags:
    - shell
    - linux
  script:
    - echo "CI_PROJECT_PATH is"
    - echo $CI_PROJECT_PATH
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_CI_WIKI" | tr -d '\r' | ssh-add - > /dev/null
    - git status
    - git log | head -n 10
    # - git remote -v
    # - git remote set-url origin ssh://git@gitlab.orr.noaa.gov:9933/${CI_PROJECT_PATH}.git
    - git remote -v
    - git stash clear
    - git stash
    - git checkout ${CI_COMMIT_BRANCH}
    - git log | head -n 10
    - git log origin/production | head -n 10
#    - git pull --allow-unrelated-histories
    - git pull
    - git stash list
    - |-
        if [[ `git stash list` ]];then
          git stash pop
        fi
#    - mkdir -p validation/${CI_COMMIT_BRANCH}/
#    - mv validation_by_* ./validation/${CI_COMMIT_BRANCH}/
    - mv validation_by_* ./validation/
    - git add -A
    - git diff-index --quiet HEAD || git commit -m 'updating validation reports'
    - git push
    - eval $(ssh-agent -k)

  except:
    - server_working_copy
  only:
    changes:
      - .gitlab-ci.yml
      - data/**/*
