stages:
  - deploy

deploy_stage:
  stage: deploy
  environment:
    name: stage
    url: https://adios-stage.orr.noaa.gov
  variables:
    REPO_LOCATION: /data/adios_oil_db/noaa-oil-data
  script:
    - pwd
    - ls -l
    - echo "cp . $REPO_LOCATION"
  tags:
    - adios-stage
    - deploy
