# variables:
#   CS_MAJOR_VERSION: 3

stages:
  - test

test_master:
  stage: test
  image: registry.orr.noaa.gov/erd/centos-conda/centos7-python3
  tags:
    - docker

  except:
    - schedules

  artifacts:
    paths:
      - oil_database/adios_db/scripts/adios_db_validation.txt
#    expire_in: 1 week

  before_script:
    - echo "ip_resolve=4" >> /etc/yum.conf
    - yum update -y
    - conda install -y python=3.9
    - conda update -y conda

  script:
    - echo "running the scripts"
    - pwd
#    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/oil_database/oildb-deploy.gi
#   note: this should be master, once things settle down.
    - git clone --depth 1 -b develop https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/oil_database/oil_database.git
    - pwd
    - ls
    - cd oil_database
    - conda install -y --file adios_db/conda_requirements.txt

    # Install the adios_db package
    - cd adios_db
    - pip install -e ./
    - cd ../../
    - adios_db_process_json ./data/oil/
    - adios_db_validate ./data/oil


