variables:
  IMAGE_NAME: 'registry.orr.noaa.gov/erd/environments/ubuntu-pixi:latest'
  GIT_DEPTH: 2

default:
  before_script:
    - pixi global install git

stages:
  - validate
  - update

validate:
  stage: validate
  image: $IMAGE_NAME

  except:
    - schedules

  artifacts:
    paths:
      - validation_by_record.md
      - validation_by_error.md
      - data

  script:
    - echo "running the scripts"
    # need frozen, so it won't try to update dev environment
    - pixi run --frozen process_json
    - pixi run --frozen production validate
  only:
    changes:
      - .gitlab-ci.yml
      - data/**/*

save normalized json formatting:
  stage: update
  image: $IMAGE_NAME

  script:
    - git config --global user.email "adios-validation-script@noaa.gov"
    - git config --global user.name "Adios Validation Script"
    - git remote set-url origin
      https://oil-db:${WRITABLE_TOKEN}@gitlab.orr.noaa.gov/${CI_PROJECT_PATH}.git
    - git stash
    - git checkout ${CI_COMMIT_BRANCH}
    - git pull
    - |-
      if [[ `git stash list` ]];then
        git stash pop
        git add data
        git commit -m "normalize json formatting"
        git push
      fi

  only:
    changes:
      - .gitlab-ci.yml
      - data/**/*

update_validation_report:
  variables:
    GIT_STRATEGY: clone

  stage: update

  image: $IMAGE_NAME

  script:
    - git config --global user.email "adios-validation-script@noaa.gov"
    - git config --global user.name "Adios Validation Script"
    - git clone
      https://oil-db:${WRITABLE_TOKEN}@gitlab.orr.noaa.gov/${CI_PROJECT_PATH}.wiki.git
    - mkdir -p ${CI_PROJECT_NAME}.wiki/validation_reports/${CI_COMMIT_BRANCH} &&
      cp validation_by_* $_
    - ls -la ${CI_PROJECT_NAME}.wiki/validation_reports/${CI_COMMIT_BRANCH}
    - cd ${CI_PROJECT_NAME}.wiki
    - git add -A
    - git diff-index --quiet HEAD || git commit -m 'updating validation reports
      on wiki'
    - git push

  except:
    - server_working_copy
    - /^\d{4}/\d{2}/\d{2}_\d{2};\d{2}$/

  only:
    changes:
      - .gitlab-ci.yml
      - data/**/*
