[workspace]
authors = ["Chris Barker <Chris.Barker@noaa.gov>"]
channels = ["conda-forge"]
name = "noaa-oil-data"
platforms = ["osx-64", "linux-64", "win-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
adios_db = ">=1.2.7,<2"
ipython = "*"
