"""
generate some stats generated by:

git diff  --name-status Before-Duplicate-Removal > file_stats.txt
"""

add = []
rem = []
for line in open('file_stats.txt'):
    if line[0] == "D":
        print(line)
        if "AD0" in line:
            rem.append(line)
    elif line[0] == "A":
        add.append(line)

# = [line for line in files if line.startswith("D") ]
print("total number of files added", len(add))
print("total number of AD files removed", len(rem))

# write out IDs as a file

with open("deleted_adios_records.txt", 'w') as outfile:
    outfile.write("IDs of ADIOS records deleted in duplicate removal:\n")
    for rec in rem:
        outfile.write(rec.split("/AD/")[1])








